- src/components/calendar/Calendar.jsx
- src/components/calendar/List.jsx
- src/components/calendar/Modal.jsx
- src/components/stastics/Circle.jsx
- src/components/stastics/Sticks.jsx
- src/pages/Main.jsx
Feat(fe): 컴포넌트 및 페이지 폴더, 파일 생성
> Feat(fe): 컴포넌트 및 페이지 폴더, 파일 생성

- package-lock.json
- package.json
- src/components/main/calendar/TheCalendar.jsx
- src/components/main/list/Details.jsx
- src/utils/format.js
> Fix(fe): calendar 정보 출력 오류 수정

- src/App.css
- src/App.js
- src/components/calendar/CreateModal.jsx
- src/components/calendar/ItemList.jsx
- src/components/common/TheHeader.jsx
- src/components/main/SubTabs.jsx
- src/components/user/User.jsx
> 'Style(fe):컴포넌트 디자인 수정'

- src/components/stastics/PeriodChart.jsx
- src/components/stastics/TotalAmountChart.jsx
- src/components/stastics/TotalCategoryChart.jsx
> Taeuk statistics

- src/App.js
- src/components/main/list/Details.jsx
- src/components/search/Search.jsx
> Fix(fe): 검색탭 목록출력 오류 수정

- src/components/calendar/CreateModal.jsx
- src/components/calendar/ItemList.jsx
- src/components/main/calendar/TheCalendar.jsx
- src/components/main/list/Details.jsx
- src/components/search/Search.jsx
Fix(fe): 검색탭 출력수정, 지출내역수정시 setList오류 수정, 지출내역 금액 입력시 숫자 외 입력 안되게 수정
> Fix(fe): 검색탭 출력수정, 지출내역수정시 setList오류 수정, 지출내역 금액 입력시 숫자 외 입력 안되게 수정

- netlify.toml
- package.json
배포테스트(fe): netlify.toml파일추가 및 build명령어 수정
> 배포테스트(fe): netlify.toml파일추가 및 build명령어 수정

- netlify.toml
> 배포테스트(fe): netlify.toml수정

- public/index.html
> Fix(fe): index.html 수정

- src/components/main/list/Details.jsx
- src/components/search/Search.jsx
> Fix(fe):충돌 해결

- netlify.toml
- src/api/requests.js
- src/components/calendar/CreateModal.jsx
- src/components/calendar/ItemList.jsx
- src/components/search/Search.jsx
- src/components/stastics/PeriodChart.jsx
- src/components/stastics/TotalAmountChart.jsx
- src/components/stastics/TotalCategoryChart.jsx
> Fix(fe): api주소 변경 후 배포테스트1

- netlify.toml
- src/functions/proxy.js
> Fix(fe): api수정 후 배포테스트2

- src/api/requests.js
- src/components/calendar/CreateModal.jsx
- src/components/calendar/ItemList.jsx
- src/components/search/Search.jsx
- src/components/stastics/PeriodChart.jsx
- src/components/stastics/TotalAmountChart.jsx
- src/components/stastics/TotalCategoryChart.jsx
> Fix(fe): api수정 후 배포테스트5

- _headers
- netlify.toml
> Fix(fe): api수정 후 배포테스트6

- _headers
- netlify.toml
> Fix(fe): api수정 후 배포테스트7

- src/components/calendar/ItemList.jsx
- src/components/search/Search.jsx
Fix(fe): 검색탭 api오류 수정 및 수정삭제 후 새로출력 수정
> Fix(fe): 검색탭 api오류 수정 및 수정삭제 후 새로출력 수정

- src/App.css
> Fix(fe): z-index 수정

- src/App.css
- src/components/common/TheHeader.jsx
- src/components/main/calendar/CreateModal.jsx
> Fix(fe):z-index 수정

- src/components/common/TheHeader.jsx
> Fix(fe): header변경

- package-lock.json
- package.json
- public/index.html
- src/App.css
- src/App.js
- src/components/main/calendar/CreateModal.jsx
- src/components/main/calendar/ItemList.jsx
- src/components/main/calendar/TheCalendar.jsx
- src/components/main/list/Details.jsx
- src/components/search/Search.jsx
- src/components/stastics/ChartWrapper.css
- src/components/stastics/TotalAmountChart.css
- src/components/stastics/TotalAmountChart.jsx
- src/components/stastics/TotalCategoryChart.jsx
- src/components/user/User.jsx
> Fix(fe):반응형 디자인 수정
